
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: prueba
  username: cristobal
  password: admin1234
  host: localhost
  port: 5432
  
test:
  <<: *default
  database: prueba_rails01_test
  username: cristobal
  password: admin1234
  host: localhost

production:
  <<: *default
  database: prueba_rails01_production
  username: prueba_rails01
  password: <%= ENV["PRUEBA_RAILS01_DATABASE_PASSWORD"] %>
